---
# Common variables for all lab VMs

# Rocky Linux mirror (change to local mirror for speed)
rocky_mirror: "https://download.rockylinux.org"

# Private registry details
k8s_host:               "{{ hostvars['lab-k8s']['ansible_host'] }}"
private_registry_host:  "{{ hostvars['lab-devtools']['ansible_host'] }}"
private_registry_port:  "5000"
private_registry_url:   "{{ private_registry_host }}:{{ private_registry_port }}"

# Kubernetes versions
rke2_version: "v1.30.4+rke2r1"
rancher_version: "2.9.2"
cert_manager_version: "v1.15.3"
helm_version: "v3.16.1"

# Rancher hostname (add to /etc/hosts or real DNS)
rancher_hostname: "rancher.lab.local"
rancher_bootstrap_password: "Admin1234!"   # Change this!

# ArgoCD
argocd_chart_version: "7.7.3"
argocd_hostname: "argocd.lab.local"

# Tools versions
kubectl_version: "v1.30.4"
