---
# Common variables for all lab VMs

# Rocky Linux mirror (change to local mirror for speed)
rocky_mirror: "https://download.rockylinux.org"

# Private registry details
k8s_host:               "{{ hostvars['lab-k8s']['ansible_host'] }}"
private_registry_host:  "{{ hostvars['lab-devtools']['ansible_host'] }}"
private_registry_port:  "5000"
private_registry_url:   "{{ private_registry_host }}:{{ private_registry_port }}"

# Kubernetes versions
rke2_version: "v1.34.5+rke2r1"
rancher_version: "2.13.3"
cert_manager_version: "v1.19.4"
helm_version: "v4.1.3"
k9s_version: "v0.50.18"

# Rancher hostname (add to /etc/hosts or real DNS)
rancher_hostname: "rancher.lab"
rancher_bootstrap_password: "Admin1234!"   # Change this!

# ArgoCD
argocd_chart_version: "7.7.3"
argocd_hostname: "argocd.lab"

# Pi-hole
pihole_version:      "2025.03.0"    # Pi-hole v6 — check hub.docker.com/r/pihole/pihole for latest
pihole_web_port:     "8080"
pihole_web_password: "Admin1234!"   # Change this!

# Pi-hole local DNS records — add new lab entries here
pihole_dns_records:
  lab-devtools:             "{{ private_registry_host }}"
  lab-devtools.lab:   "{{ private_registry_host }}"
  lab-k8s:                  "{{ k8s_host }}"
  lab-k8s.lab:        "{{ k8s_host }}"
  rancher.lab:        "{{ k8s_host }}"
  argocd.lab:         "{{ k8s_host }}"

# Tools versions
kubectl_version: "v1.34.5"
