---
all:
  vars:
    ansible_user: ansible
    ansible_become: true
    ansible_become_method: sudo
    ansible_ssh_private_key_file: ~/.ssh/lab_rsa
    ansible_python_interpreter: /usr/bin/python3

  children:
    devtools:
      hosts:
        lab-devtools:
          ansible_host: 192.168.100.10
          registry_port: 5000
          registry_hostname: lab-devtools

    k8s_nodes:
      hosts:
        lab-k8s:
          ansible_host: 192.168.100.20
          rke2_type: server
          registry_mirror_url: "http://{{ private_registry_url }}"
